# Generated by Django 4.2.3 on 2023-08-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='direccion',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='telefono',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
